server:
  port: 8083

spring:
  application:
    name: fakepanshi
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/baichuan
  #      host: 127.0.0.1
  #      port: 27017
  #      database: baichuan
  #      username:
  #      password:

  # jdbc_config   datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/persontest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    hikari:
      # Hikari will use the above plus the following to setup connection pooling
      minimum-idle: 3
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCPPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1




